insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('01','1',null,'COORDINADOR ','Telchac','Telchac','Telchac','','9841572615','7','20','15','17','Orion','3','859','ALBAÑIL','44','F','SSPCNN77082931M000','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('001','2','01','ACTIVISTA','TEP','EK','CLEINI NALLELI','CLEINI','','S/N','29','20','22','GUADALUPE','45','859','Empleada','34','F',' TPEKCL86051231M900','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0001','3','001','PROMOVIDOS','Prueba1','Prueba2','Prueba3','','','','','','','','','859','','35','F','AAAAAAAAAAAAAAA','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0002','3','001','PROMOVIDOS','Prueba1','Prueba2','Prueba3','','','','','','','','','859','','35','F','AAAAAAAAAAAAAAA','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('002','2','01','ACTIVISTA','CRUZ','CHALE','CRISTINA GUADALUPE','CRISTINA','999 199 1891','S/N','25','32','34','FATIMA ','9','859','','35','F',' CRCHCR85091631M200','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0003','3','002','PROMOVIDOS','CHALE ','BACAB','NASARIA LUCILA ','','999 199 1891','S/N','25','32','34','FATIMA ','9','859','Ama de casa','62','F','AAAAAAAAAAAAAA1','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0004','3','002','PROMOVIDOS','AGUILAR','CHALE','RONALD RENE','','999 199 1891','S/N','34','23','21','FATIMA ','','859','Empleado','36','M','AAAAAAAAAAAAAA2','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0005','3','002','PROMOVIDOS','CHALE ','','MARIA DE LA LUZ','','999 199 1891','S/N','34','23','21','FATIMA ','','859','Ama de casa','66','F','AAAAAAAAAAAAAA3','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0006','3','002','PROMOVIDOS','ROLDAN ','CHALE','JESUS SALATIEL','','999 199 1891','S/N','34','23','21','FATIMA ','','859','Empleado','22','M','AAAAAAAAAAAAAA4','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0007','3','002','PROMOVIDOS','PLAZA','GUERRERO','JORGE ','','999 199 1891','S/N','25','32','34','FATIMA ','9','859','Comerciante','40','M','AAAAAAAAAAAAAA5','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0008','3','002','PROMOVIDOS','CRUZ','CHALE','MARIA HERMENEJIDA ','','999 256 5034','S/N','25','32','34','FATIMA ','9','859','empleada','45','F','AAAAAAAAAAAAAA6','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0009','3','002','PROMOVIDOS','ALAMILLA','NOH','CARLOS MANUEL','','999 199 1891','S/N','29','2D','2E','SAN NICOLAS','','860','ALBAÑIL','24','M','AAAAAAAAAAAAAA7','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0010','3','002','PROMOVIDOS','RIVERA','CENTENO','REYES DE JESUS ','','999 199 1891','S/N','34','25','27','','','859','Ama de casa','40','F','AAAAAAAAAAAAAA8','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0011','3','002','PROMOVIDOS','TUN','UC','FELICIANA','','999 199 1891','S/N','25','38','36','FATIMA ','6','859','Ama de casa','40','F',' TNUCFL60102031M300','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('003','2','01','ACTIVISTA','YHUIT','CERVANTES','FELIPA DEL SOCORRO','FELIPA','999 255 9868','S/N','27','10','6','San Nicolas ','67','860','','32','F',' YHCRFL88050931M800','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0012','3','003','PROMOVIDOS','GURUBEL','GALAZ','CARLOS ALEJANDRO','','999 449 1480','S/N','','','','','','860','','40','M','BBBBBBBBBBBBBBBB2','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0013','3','003','PROMOVIDOS','CERVANTES','POOL','SOCORRO','','999 262 0464','S/N','','','','','','860','','40','F','BBBBBBBBBBBBBBBB3','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0014','3','003','PROMOVIDOS','EUAN ','CERVANTES','JOSE FELICIANO','','999 458 7781','S/N','','','','','','860','','40','M','BBBBBBBBBBBBBBBB4','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0015','3','003','PROMOVIDOS','BRITO','DZIB','FELICIANA','','999 993 5226','S/N','','','','','','860','','40','F','BBBBBBBBBBBBBBBB5','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0016','3','003','PROMOVIDOS','EUAN ','CERVANTES','NORA','','999 246 9265','S/N','','','','','','860','','40','F','BBBBBBBBBBBBBBBB6','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0017','3','003','PROMOVIDOS','BALAM','EUAN','ALEJANDRA','','999 246 9265','S/N','','','','','','860','','40','F','BBBBBBBBBBBBBBBB7','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0018','3','003','PROMOVIDOS','YHUIT','CERVANTES','ROSSANA','','999 279 9816','S/N','','','','','','860','','40','F','BBBBBBBBBBBBBBBB8','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0019','3','003','PROMOVIDOS','MAC','','MARTIN','','999 279 9816','S/N','','','','','','860','','40','M','BBBBBBBBBBBBBBBB9','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0020','3','003','PROMOVIDOS','MAC','YHUIT','NELLY  ','','991 111 7162','S/N','','','','','','860','','40','F','BBBBBBBBBBBBBBBB10','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0021','3','003','PROMOVIDOS','EUAN ','CERVANTES','OMAR','','999 542 8575','S/N','','','','','','860','','40','M','BBBBBBBBBBBBBBBB11','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0022','3','003','PROMOVIDOS','LEON ','BASTO','INES ','','999 134 4064','S/N','','','','','','860','','40','F','BBBBBBBBBBBBBBBB12','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0023','3','003','PROMOVIDOS','YHUIT','LEON','LEYDI','','999 262 2426','S/N','','','','','','860','','40','F','BBBBBBBBBBBBBBBB13','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0024','3','003','PROMOVIDOS','YHUIT','LEON','OMAR','','999 192 4660','S/N','','','','','','860','','40','M','BBBBBBBBBBBBBBBB14','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0025','3','003','PROMOVIDOS','YHUIT','CERVANTES','MARIELA','','991 110 4051','S/N','','','','','','860','','40','F','BBBBBBBBBBBBBBBB15','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0026','3','003','PROMOVIDOS','EUAN ','CUTZ','JUAN CARLOS','','999 268 3947','S/N','','','','','','860','','40','M','BBBBBBBBBBBBBBBB16','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0027','3','003','PROMOVIDOS','YAH','CAMPOS','CINTIA KARINA','','999 115 2488','S/N','','','','','','860','','40','F','BBBBBBBBBBBBBBBB17','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0028','3','003','PROMOVIDOS','EK ','VAZQUEZ','JULIO','','','S/N','','','','','','860','','40','M','BBBBBBBBBBBBBBBB18','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0029','3','003','PROMOVIDOS','EK ','VAZQUEZ','ALBERTH','','','S/N','','','','','','860','','40','M','BBBBBBBBBBBBBBBB19','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0030','3','003','PROMOVIDOS','EK ','VAZQUEZ','ANA','','','S/N','','','','','','860','','40','F','BBBBBBBBBBBBBBBB20','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0031','3','003','PROMOVIDOS','ZOZAYA','','GABRIELA','','999 127 2562','S/N','','','','','','860','','40','F','BBBBBBBBBBBBBBBB21','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0032','3','003','PROMOVIDOS','MONTALVO','','ANGEL','','999 127 2562','S/N','','','','','','860','','40','M','BBBBBBBBBBBBBBBB22','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0033','3','003','PROMOVIDOS','EK ','VAZQUEZ','LUIS','','999 199 7409','S/N','','','','','','860','','40','M','BBBBBBBBBBBBBBBB23','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0034','3','003','PROMOVIDOS','COHUO','','CELIA','','991 959 6257','S/N','','','','','','860','','40','F','BBBBBBBBBBBBBBBB24','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0035','3','003','PROMOVIDOS','LEON ','','MARTIN','','991 114 0110','S/N','','','','','','860','','40','M','BBBBBBBBBBBBBBBB25','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0036','3','003','PROMOVIDOS','EUAN ','ARGAEZ ','MARCOS','','999 550 3174','S/N','','','','','','860','','40','M','BBBBBBBBBBBBBBBB26','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0037','3','003','PROMOVIDOS','CATZIN','','MALENA','','999 550 3174','S/N','','','','','','860','','40','F','BBBBBBBBBBBBBBBB27','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('004','2','01','ACTIVISTA','POVEDANO','LUNA','CARLOS VALENTIN','CARLOS','991 108 7124','S/N','27','12','14','TELCHAC PTO','46','860','Carpintero','49','M',' PVLNCR72021431H300','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0038','3','004','PROMOVIDOS','POVEDANO','LUNA','ELSY MARGARITA','ELSY','991 108 7124','S/N','21','22','24','CENTRO','58','859','Comerciante','54','F',' PVLNEL67101931M300','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0039','3','004','PROMOVIDOS','LUNA ','SANCHEZ','EULOGIA','','991 108 7124','S/N','21','22','24','CENTRO','58','859','Ama de casa','50','F','CCCCCCCCCCCCCCCCC1','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0040','3','004','PROMOVIDOS','CRIOLLO','MERINO','JOSE','','991 108 7124','S/N','21','22','24','CENTRO','58','859','Comerciante','50','M','CCCCCCCCCCCCCCCCC2','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0041','3','004','PROMOVIDOS','DIAZ','POVEDANO','FRANKRIN EDUARDO','','991 108 7124','S/N','21','22','24','CENTRO','58','859','Comerciante','50','M','CCCCCCCCCCCCCCCCC3','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0042','3','004','PROMOVIDOS','CHAY','LUNA ','ROBERTO','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC4','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0043','3','004','PROMOVIDOS','MARRUFO','VARGAS','FRANCISCA','','991 108 7124','S/N','','','','','','860','','50','F','CCCCCCCCCCCCCCCCC5','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0044','3','004','PROMOVIDOS','CHAY','MARRUFO','LEYDI','','991 108 7124','S/N','','','','','','860','','50','F','CCCCCCCCCCCCCCCCC6','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0045','3','004','PROMOVIDOS','CHAY','MARRUFO','PAMELA','','991 108 7124','S/N','','','','','','860','','50','F','CCCCCCCCCCCCCCCCC7','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0046','3','004','PROMOVIDOS','CHAY','MARRUFO','YORDI','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC8','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0047','3','004','PROMOVIDOS','LUNA','SANCHEZ','FERNANDO','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC9','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0048','3','004','PROMOVIDOS','LUNA','','JUAQUIN','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC10','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0049','3','004','PROMOVIDOS','RAMIREZ','','ROSARIO','','991 108 7124','S/N','','','','','','860','','50','F','CCCCCCCCCCCCCCCCC11','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0050','3','004','PROMOVIDOS','LUNA','','REYES','','991 108 7124','S/N','','','','','','860','','50','F','CCCCCCCCCCCCCCCCC12','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0051','3','004','PROMOVIDOS','LEYVA','','JORGE ','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC13','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0052','3','004','PROMOVIDOS','CETZ ','','LADI CARLOS','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC14','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0053','3','004','PROMOVIDOS','CAMARA','','GLORIA  ','','991 108 7124','S/N','','','','','','860','','50','F','CCCCCCCCCCCCCCCCC15','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0054','3','004','PROMOVIDOS','CETZ ','','ANGEL','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC16','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0055','3','004','PROMOVIDOS','CETZ ','','JULIO','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC17','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0056','3','004','PROMOVIDOS','CETZ ','','CARMEN','','991 108 7124','S/N','','','','','','860','','50','F','CCCCCCCCCCCCCCCCC18','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0057','3','004','PROMOVIDOS','CETZ ','','MARLENE','','991 108 7124','S/N','','','','','','860','','50','F','CCCCCCCCCCCCCCCCC19','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0058','3','004','PROMOVIDOS','TUN ','','JOSE','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC20','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0059','3','004','PROMOVIDOS','POVEDANO','CHAY','JAEL LUCELI','','991 108 7124','S/N','','','','','','860','','50','F','CCCCCCCCCCCCCCCCC21','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0060','3','004','PROMOVIDOS','SANCHEZ','','CRISTIAN','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC22','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0061','3','004','PROMOVIDOS','CANTO','','ANDREA  ','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC23','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0062','3','004','PROMOVIDOS','SALAZAR','MENDOZA','CECILIA','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC24','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0063','3','004','PROMOVIDOS','CETINA ','SALAZAR','TUNIN','','991 108 7124','S/N','','','','','','860','','50','F','CCCCCCCCCCCCCCCCC25','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0064','3','004','PROMOVIDOS','ORTIZ','CHAY','FRANCISCO  ','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC26','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0065','3','004','PROMOVIDOS','GODINEZ','','JONATHAN','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC27','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0066','3','004','PROMOVIDOS','CAB','SOSA','CLEMENTE','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC28','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0067','3','004','PROMOVIDOS','CAB','SOSA','JULIO','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC29','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0068','3','004','PROMOVIDOS','CAB','SOSA','CRISTOBAL','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC30','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0069','3','004','PROMOVIDOS','AVILA','','OLDA MARIA','','991 108 7124','S/N','','','','','','860','','50','F','CCCCCCCCCCCCCCCCC31','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0070','3','004','PROMOVIDOS','BALAM','','JORGE ','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC32','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0071','3','004','PROMOVIDOS','BALAM','','SHIRLEY','','991 108 7124','S/N','','','','','','860','','50','F','CCCCCCCCCCCCCCCCC33','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0072','3','004','PROMOVIDOS','CHAY','','EDGAR','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC34','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0073','3','004','PROMOVIDOS','CHALE ','','MARISOL','','991 108 7124','S/N','','','','','','860','','50','F','CCCCCCCCCCCCCCCCC35','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0074','3','004','PROMOVIDOS','BAAS','','ELUTERIO','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC36','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0075','3','004','PROMOVIDOS','MARFIL','','JAIME','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC37','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0076','3','004','PROMOVIDOS','CARRILLO','','FERNANDO','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC38','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0077','3','004','PROMOVIDOS','BALAM','','NAYELI','','991 108 7124','S/N','','','','','','860','','50','F','CCCCCCCCCCCCCCCCC39','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0078','3','004','PROMOVIDOS','CAHCNE','','OMAR','','991 108 7124','S/N','','','','','','860','','50','M','CCCCCCCCCCCCCCCCC40','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0079','3','004','PROMOVIDOS','CHAY ','CETINA','JORGE HUMBERTO','SARGAZO','991 108 7124','S/N','30','25','','FATIMA','12','859','','50','M',' CHCTJR65041831H400','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0080','3','004','PROMOVIDOS','LUNA ','CETZ','JOSE ALFREDO','PAKA','991 108 7124','S/N','34','25','27','FATIMA','4','859','','50','M',' LNCTAL99081931H200','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0081','3','004','PROMOVIDOS','MEDINA','ESCALANTE','VICTOR SAUL','MALIX','991 108 7124','S/N','23','','','PLAYA BONITA','9999','860','','50','M',' MDESVC81072831H001','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0082','3','004','PROMOVIDOS','CATZIN','CHALE','EDGAR','MORZA','991 108 7124','S/N','23','','','PLAYA BONITA','9999','860','','50','M',' CHCTED79101931H400','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('005','2','01','ACTIVISTA','CERVANTES','VAZQUEZ','ISMAEL','ISMAEL','999 172 9189','105','23','22','24','SAN NICOLAS','52','859','','70','M',' CTCHYS51032431H500','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0083','3','005','PROMOVIDOS','VAZQUEZ','MAY','MARIANITA','','999 172 9189','','','','','','','859','','70','F','DDDDDDDDDDDDDDDDDDD1','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0084','3','005','PROMOVIDOS','POOL','CERVANTES','ANDREA JAQUELINE','','999 172 9189','','','','','','','859','','70','F','DDDDDDDDDDDDDDDDDDD2','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0085','3','005','PROMOVIDOS','POOL','CERVANTES','JOHANA JARED','','999 172 9189','','','','','','','859','','70','F','DDDDDDDDDDDDDDDDDDD3','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0086','3','005','PROMOVIDOS','CANTO','','NERY','','999 172 9189','','','','','','','859','','70','F','DDDDDDDDDDDDDDDDDDD4','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0087','3','005','PROMOVIDOS','CERVANTES','VAZQUEZ','JOSE MARIA','','999 172 9189','','','','','','','859','','70','F','DDDDDDDDDDDDDDDDDDD5','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0088','3','005','PROMOVIDOS','CHALE ','BACAB','JOSE ANGEL','','999 172 9189','','','','','','','859','','70','M','DDDDDDDDDDDDDDDDDDD6','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0089','3','005','PROMOVIDOS','ESTRELLA','ESCALANTE','ELMIR EMMANUEL','','999 172 9189','','','','','','','859','','70','M','DDDDDDDDDDDDDDDDDDD7','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0090','3','005','PROMOVIDOS','CUPUL','CETZ','SAYRI DEL SOCORRO','','999 172 9189','','','','','','','859','','70','F','DDDDDDDDDDDDDDDDDDD8','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0091','3','005','PROMOVIDOS','GOMEZ','','SANTA','','999 172 9189','','','','','','','859','','70','F','DDDDDDDDDDDDDDDDDDD9','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0092','3','005','PROMOVIDOS','POVEDANO','SALAZAR','ANDREY','','999 172 9189','','','','','','','859','','70','F','DDDDDDDDDDDDDDDDDDD10','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0093','3','005','PROMOVIDOS','CHAY','PERALTA','LUCIA ','','999 172 9189','','','','','','','859','','70','F','DDDDDDDDDDDDDDDDDDD11','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0094','3','005','PROMOVIDOS','CETINA ','BAAS','AMILCAR','','999 172 9189','','','','','','','859','','70','M','DDDDDDDDDDDDDDDDDDD12','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0095','3','005','PROMOVIDOS','LORA ','AKE','JESUS ALEXANDER','','999 172 9189','','','','','','','859','','70','M','DDDDDDDDDDDDDDDDDDD13','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0096','3','005','PROMOVIDOS','PECH','NAH','JESUS EFRAIN','','999 172 9189','','','','','','','859','','70','M','DDDDDDDDDDDDDDDDDDD14','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0097','3','005','PROMOVIDOS','CAMPOS','','PABLO','','999 172 9189','','','','','','','859','','70','M','DDDDDDDDDDDDDDDDDDD15','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0098','3','005','PROMOVIDOS','VELUETA','','CARLOS MANUEL','','999 172 9189','','','','','','','859','','70','M','DDDDDDDDDDDDDDDDDDD16','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0099','3','005','PROMOVIDOS','PEREZ','HAU','CONCEPCION','','999 172 9189','','','','','','','859','','70','F','DDDDDDDDDDDDDDDDDDD17','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0100','3','005','PROMOVIDOS','PACAB','EUAN','JOSE MANUEL','COQUERO','999 172 9189','','','','','','','859','','70','M','DDDDDDDDDDDDDDDDDDD18','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0101','3','005','PROMOVIDOS','CAN ','CASTILLO','XAVIER DE JESUS','','999 172 9189','','','','','','','859','','70','M','DDDDDDDDDDDDDDDDDDD19','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('006','2','01','ACTIVISTA','CANCHE','NAAL','SILVIA MARLENE','MAGALI','999 495 0999','S/N','29','24','26','GUADALUPE','39','859','Ama de casa','34','F',' CNNLSL74092431M400','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0102','3','006','PROMOVIDOS','QUINTAL ','PERAZA','MAURA DE LOS ANGELES','MAIRI','999 495 0999','S/N','29','24','26','GUADALUPE','39','859','Ama de casa','57','F',' QNPRMR64092231M700','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0103','3','006','PROMOVIDOS','CANCHE','DOMINGUEZ','JOSE UBALDO','UBALDO','999 495 0999','S/N','29','24','26','GUADALUPE','39','859','PESCADOR','33','M',' CNDMUB88051631H700','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0104','3','006','PROMOVIDOS','CANCHE ','QUINTAL','PERLA DEL CARMEN','PERLA','999 495 0999','S/N','29','24','26','GUADALUPE','39','859','Estudiante ','29','F',' CNQNPR92040731M600','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0105','3','006','PROMOVIDOS','CANCHE','CHAY','JOSE UBALDO','UVA','999 495 0999','S/N','29','24','26','GUADALUPE','39','859','PESCADOR','60','M',' CNCHUB61051631H000','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0106','3','006','PROMOVIDOS','RODRIGUEZ','CANCHE','GLORIA MARIA ','GLORIA','999 495 0999','S/N','29','24','26','GUADALUPE','39','859','Ama de casa','39','F',' RDCNGL82041131M400','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0107','3','006','PROMOVIDOS','BALAM','BALAM','JOSE GABRIEL','GABRIEL','999 495 0999','S/N','29','24','26','GUADALUPE','39','859','PESCADOR','43','M',' BLBLGB78050831H100','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0108','3','006','PROMOVIDOS','BALAM','RODRIGUEZ','INGLI JAFET','INGLI','999 495 0999','S/N','29','24','26','GUADALUPE','39','859','Ama de casa','22','F',' BLRDIN99030131M900','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0109','3','006','PROMOVIDOS','BALAM','RODRIGUEZ','DARINKA YURAY','DARINKA','999 495 0999','S/N','29','24','26','GUADALUPE','39','859','Estudiante ','20','F',' BLRDDR01080831M500','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0110','3','006','PROMOVIDOS','DAVILA','RAMOS','DANIEL','DANIEL','999 495 0999','S/N','27','40','42','SAN CLEMENTE','95','859','PESCADOR','40','M',' DVRMDN81022707H000','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0111','3','006','PROMOVIDOS','DAVILA','CANCHE','BRYAN DANIEL','BRYAN','999 495 0999','S/N','27','40','42','SAN CLEMENTE','95','859','PESCADOR','19','M',' DVCNBR02081531H100','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0112','3','006','PROMOVIDOS','CANCHE','NAAL','MARIA DE LOURDES','LULA','999 495 0999','S/N','27','40','42','SAN CLEMENTE','95','859','Ama de casa','44','F',' CNNLLR77093031M700','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0113','3','006','PROMOVIDOS','CANCHE','CHI','CARLOS','','999 495 0999','S/N','29','24','26','GUADALUPE','39','859','PESCADOR','68','M',' CNCHCR53110431H301','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0114','3','006','PROMOVIDOS','NAAL','E INTERIAN','SILVIA MARIA','SILVIA','999 495 0999','S/N','29','24','26','GUADALUPE','39','859','Ama de casa','64','F',' NLEXSL57110331M900','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0115','3','006','PROMOVIDOS','CANCHE','Y CHI','ELEUTERIA','','999 495 0999','S/N','29','26','28','GUADALUPE','39','859','Ama de casa','73','F',' CNCHEL48022031M501','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0116','3','006','PROMOVIDOS','MAY','MUKUL','MARIA JUSTINA','','999 495 0999','S/N','29','24','26','GUADALUPE','39','859','Ama de casa','41','F',' MYMKJS80103031M500','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0117','3','006','PROMOVIDOS','CAB','SOSA','MILDRED ANGELICA','','999 495 0999','S/N','29','2C','','SAN NICOLAS','103','860','Ama de casa','40','F',' CBSSML81012031M400','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0118','3','006','PROMOVIDOS','CANCHE','NAAL','REIMIGIO','','999 495 0999','S/N','29','2','','SAN NICOLAS','103','860','PESCADOR','45','M',' CNNLRM76100131H300','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0119','3','006','PROMOVIDOS','LUNA','PECH','ELVIRA ROSAURA','','999 495 0999','S/N','29','30','32','GUADALUPE','39','859','Ama de casa','50','F',' LNPCEL71012531M600','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0120','3','006','PROMOVIDOS','BAAS','CHALE','MARIA SANTOS EDMUNDA','SANTOS','999 203 7499','S/N','29','28','30','FATIMA','39','859','Ama de casa','57','F',' BSCHSN64111631M400','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0121','3','006','PROMOVIDOS','CRUZ','BAAS','ANDI GILARI','GILARI','999 227 3857','S/N','29','28','30','FATIMA','39','859','Ama de casa','27','F',' CRBSAN94030331M200','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0122','3','006','PROMOVIDOS','CRUZ','BAAS','SANDY ESTHER','SANDY','999 100 8067','S/N','29','28','30','FATIMA','39','859','Ama de casa','33','F',' CRBSSN88112831M300','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0123','3','006','PROMOVIDOS','VERA','KU','REYES GARPAS','','999 495 0999','S/N','29','30','','FATIMA','26','859','PESCADOR','39','M',' VRKURY82010531H300','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0124','3','006','PROMOVIDOS','PERAZA','CHAY','FRANCISCO ELISEO','','999 495 0999','S/N','29','24','26','GUADALUPE','75','859','PESCADOR','49','M',' PRCHFR72061431H300','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0125','3','006','PROMOVIDOS','LUIS','PEREZ','FERNANDO','','999 495 0999','S/N','29','30','28','GUADALUPE','39','859','PESCADOR','31','M',' LSPRFR90110830H100','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0126','3','006','PROMOVIDOS','NOH ','TEC','AMADA RAQUEL','CHUCA','','','','','','','','859','','34','F',' LSPRFR90110830H101','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0127','3','006','PROMOVIDOS','BALCAZAR','GARCIA','ERIC','','','','','','','','','859','','45','F',' LSPRFR90110830H102','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('007','2','01','ACTIVISTA','VILLANUEVA','RAMOS','DEYMI','DEYMI','999 361 2037','S/N','29','14','16','SAN NICOLAS','70','860','Ama de casa','34','F',' VLRMDY79012131M800','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0128','3','007','PROMOVIDOS','TEC ','VILLANUEVA','MARIO JONATHAN','YONI','999 255 1004','S/N','29','14','16','SAN NICOLAS','70','860','Estudiante ','20','M','TCVLMR01012631H600','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0129','3','007','PROMOVIDOS','EUAN ','VILLANUEVA','YOSWANI IMARA','IMARA','991 108 1800','S/N','29','6','10','SAN NICOLAS','71','860','Estudiante ','21','F','ENVLYS03032531M000','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0130','3','007','PROMOVIDOS','VILLANUEVA','ESTRELLA','LEAN SAHILY','sahili','999 270 1225','S/N','6','27A','27','Caridad del cobre','67','860','Empleado','21','F',' VLESLN00083031M700','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0131','3','007','PROMOVIDOS','VILLANUEVA','CEN ','REFUGIO','PANCHITO','999 361 2037','S/N','6','27A','27','Caridad del cobre','67','860','Comerciante','22','F',' VLCNRF49111131H600','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0132','3','007','PROMOVIDOS','VAZQUEZ','CETZAL','JUANA FRANCISCA','JUANITA','999 361 2037','S/N','29','6','4','SAN NICOLAS','71','860','Ama de casa','23','F',' VZCTJN67080431M800','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0133','3','007','PROMOVIDOS','POOL','Y CRUZ','EPIFANIA','FANI','999 505 1244','S/N','29','12','14','SAN NICOLAS','70','860','Ama de casa','24','F',' PLCREP58071231M300','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0134','3','007','PROMOVIDOS','TEC ','POOL','HERIBERTO','BETO','999 358 0372','S/N','29','12','14','SAN NICOLAS','70','860','albañil','25','M',' TCPLHR77031631H500','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0135','3','007','PROMOVIDOS','TEC ','TAMAYO','HERIBERTO','','991 104 0357','S/N','29','12','14','SAN NICOLAS','70','860','albañil','26','M',' TCTMHR99080331H500','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0136','3','007','PROMOVIDOS','TAMAYO ','CHIM','ANTONIA','antonia','999 361 2037','S/N','29','12','14','SAN NICOLAS','70','860','Ama de casa','27','F',' TMCHAN77011731M800','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0137','3','007','PROMOVIDOS','TEC ','VILLANUEVA','YARAJANI NAZARET','JANI','999 570 1225','S/N','29','14','16','Caridad del cobre','69','860','empleada','28','F',' TCVLYR98062831M500','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0138','3','007','PROMOVIDOS','TEC ','POOL','ALEJANDRA','ale','999 142 9823','S/N','25','6','8','SAN NICOLAS','17','860','Ama de casa','29','F',' TCPLML90043031M400','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0139','3','007','PROMOVIDOS','VILLANUEVA','RAMOS','EDMUNDO ABIMAEL','mundo','999 361 2037','S/N','6','27A','27','Caridad del cobre','67','860','albañil','30','M',' VLRMED77111331H200','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0140','3','007','PROMOVIDOS','PEREZ','DE LA CRUZ','ROBERTO ALEX','','999 361 2037','S/N','25','38','40','SAN NICOLAS','16','859','pescador','31','M',' PRCRRB95032209H700','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0141','3','007','PROMOVIDOS','VILLANUEVA','RAMOS','YADIRA','yadira','999 361 2037','S/N','29','6','10','SAN NICOLAS','71','860','empleada','32','F',' VLRMYD86051831M600','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0142','3','007','PROMOVIDOS','VILLANUEVA','ESTRELLA','LITZY LOAMMI','loami','999 361 2037','S/N','6','27A','27','Caridad del cobre','67','860','empleada','33','F',' VLESLT99070231M700','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0143','3','007','PROMOVIDOS','CUPUL','CUPUL','JOSE ISRAEL','ruco','999 743 1055','S/N','6','23','25','SAN NICOLAS','16','860','albañil','34','M',' CPCPIS76082904H201','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0144','3','007','PROMOVIDOS','EUAN ','SANCHEZ','LUIS FELIPE','','999 361 2037','S/N','18','23','25','SAN NICOLAS','60','860','','35','M',' ENSNLS91010331H500','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0145','3','007','PROMOVIDOS','CHUC','YAM','JESUS DEL CARMEN','chucho','999 361 2037','S/N','27A','26','24','CASTILLO','75','859','','36','M',' CHYMJS75021431H900','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0146','3','007','PROMOVIDOS','ESTRELLA','NOH','REBECA  ','rebeca','999 361 2037','S/N','6','27A','27','Caridad del cobre','67','860','Ama de casa','37','F',' ESNHRB79022731M700','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0147','3','007','PROMOVIDOS','TAMAYO ','CHIM','LOURDES GUADALUPE','lulu','999 353 7348','S/N','29','12','14','SAN NICOLAS','70','860','Ama de casa','38','F',' TMCHLR74032131M300','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0148','3','007','PROMOVIDOS','CANCHE','TAMAYO','JOSE EDUARDO','eduardo','999 361 2037','S/N','29','12','14','SAN NICOLAS','70','860','','39','M',' CNTMED97123031H100','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0149','3','007','PROMOVIDOS','RAMOS','MARTINEZ','MARTA FEBE','marta','991 103 4251','S/N','27A','6','10','Caridad del cobre','67','860','Comerciante','40','F',' RMMRMR57112531M400','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0150','3','007','PROMOVIDOS','PUC','CETZ ','JUAN ANTONIO','don juan','991 115 6837','S/N','29','14','16','SAN NICOLAS','42','860','','41','M',' PCCTJN60060931H500','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0151','3','007','PROMOVIDOS','SOLIS','PEREZ','BRENDA ELIZABETH','brenda','999 355 2971','S/N','29','2','2D','SAN NICOLAS','103','860','Ama de casa','42','F',' SLPRBR90102931M800','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0152','3','007','PROMOVIDOS','CETZ ','NOH','MARIA HERMELINDA','herme','999 361 2037','S/N','29','10','12','Caridad del cobre','30','860','Ama de casa','43','F',' CTNHHR73082931M000','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0153','3','007','PROMOVIDOS','HERNANDEZ','ARGUELLES','MIRIAM IVETH','miriam','999 361 2037','S/N','29','20','22','GUADALUPE','45','859','Ama de casa','44','F',' HRARMR73012627M400','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0154','3','007','PROMOVIDOS','CRUZ','ACOPA','TRINIDAD','','999 361 2037','S/N','6','29','27','Caridad del cobre','68','860','albañil','45','M',' CRACTR70040527H600','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0155','3','007','PROMOVIDOS','BALCAZAR','GARCIA','RUBI','rubi','999 361 2037','S/N','29','4','6','san nicolas','35','860','Ama de casa','46','F',' BLGRRB84111304M100','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0156','3','007','PROMOVIDOS','ALFARO','MOGUEL','MARIANA RUBI','mariana','999 361 2037','S/N','27A','6','10','Caridad del cobre','69','860','empleada','47','F',' ALMGMR94060231M300','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0157','3','007','PROMOVIDOS','ALFARO','DURAN','JOSE ENRRIQUE','','999 361 2037','S/N','27A','6','10','Caridad del cobre','68','860','','48','M',' ALDREN67071531H200','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0158','3','007','PROMOVIDOS','ALFARO','MOGUEL','ILEANA MARISOL','marisol','999 361 2037','S/N','27A','6','10','Caridad del cobre','68','860','empleada','49','F',' ALMGIL90111431M000','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0159','3','007','PROMOVIDOS','ARANA','CHUC','JAIR ABISUR','','999 361 2037','S/N','27A','6','10','Caridad del cobre','68','860','','50','M',' ARCHJR92052931H900','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0160','3','007','PROMOVIDOS','ARANA ','CHUC','KATHIA ADIELI','katia','999 361 2037','S/N','27A','6','10','Caridad del cobre','68','860','','51','F',' ARCHKT94071131M300','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0161','3','007','PROMOVIDOS','ARANA','CHUC','RUTH ODALIZ','adaliz','999 361 2037','S/N','8','27','25','Caridad del cobre','26','860','Ama de casa','52','F',' ARCHRT88101531M500','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0162','3','007','PROMOVIDOS','BASS','CHALE','JOSE YSABEL','sabuca','999 361 2037','S/N','27A','8','6','Caridad del cobre','68','860','Comerciante','53','M',' BSCHYS56110531H000','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0163','3','007','PROMOVIDOS','GARCIA','CORDOVA','RICARDO','hueso','999 361 2037','S/N','27','6','10','Caridad del cobre','67','860','albañil','54','M',' GRCRRC73103004H100','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0164','3','007','PROMOVIDOS','UITZ','FLORES','MARIA DE LOURDES','lurdes','999 361 2037','S/N','27','6','10','Caridad del cobre','67','860','Ama de casa','55','F',' UTFLLR78070231M700','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0165','3','007','PROMOVIDOS','CHALE ','UCH','CELSO NORBERTO','celso','999 361 2037','S/N','29','6','10','Caridad del cobre','68','860','Profesor','56','M',' CHUCCL79040631H800','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0166','3','007','PROMOVIDOS','ACOSTA','CEN','WENDY DEL SOCORRO','wendy','999 361 2037','S/N','29','6','10','Caridad del cobre','68','860','Ama de casa','57','F',' ACCNWN78120531M701','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0167','3','007','PROMOVIDOS','POOL','TEC','FABIOLA MARISOL','marisol','999 361 2037','S/N','29','6','10','Caridad del cobre','71','860','Ama de casa','58','F',' PLTCFB96040431M400','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0168','3','007','PROMOVIDOS','TAMAYO ','CHUC','ANTONIO RUBI','rubi','999 361 2037','S/N','29','6','10','Caridad del cobre','71','860','Ama de casa','59','F',' TMCHAN91061387M000','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0169','3','007','PROMOVIDOS','UITZ','FLORES','MARIA LETICIA','','999 361 2037','S/N','6','25','27','san nicolas','24','860','Ama de casa','60','F',' UTFLLT76121531M500','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0170','3','007','PROMOVIDOS','POOL','CERVANTES','ANDREA JAQUELINE','andrea','999 361 2037','S/N','29','10','8','Caridad del cobre','71','860','Ama de casa','61','F',' PLCRAN98090731M100','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0171','3','007','PROMOVIDOS','CERVANTES','VAZQUEZ','MARIA MAGDALENA','','999 361 2037','S/N','29','10','8','Caridad del cobre','71','860','Ama de casa','62','F',' CRVZMG76031331M500','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0172','3','007','PROMOVIDOS','POOL','CERVANTES','JOHANA YARETH','johana','999 361 2037','S/N','29','8','10','Caridad del cobre','71','860','Ama de casa','63','F',' PLCRJH00072431M800','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0173','3','007','PROMOVIDOS','POOL','TEC','SELENE ARACELI','selene','999 361 2037','S/N','29','12','14','san nicolas','70','860','Ama de casa','64','F',' PLTCSL93081331M200','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0174','3','007','PROMOVIDOS','VILLANUEVA','RAMOS','SAMUEL FRANCISCO','casco','999 361 2037','S/N','29','12','14','san nicolas','70','860','albañil','65','M',' VLRMSM83111631H101','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0175','3','007','PROMOVIDOS','PUC','PALACIOS','MARIA ROSALVA','','999 361 2037','S/N','29','14','16','san nicolas','69','860','Ama de casa','66','F',' PCPLRS65082931M800','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0176','3','007','PROMOVIDOS','ANGULO','CANUL','EDWIN DAVID','edwin','999 361 2037','S/N','29','14','16','SAN NICOLAS','69','860','','67','M',' ANCNED93072531H500','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0177','3','007','PROMOVIDOS','ANGULO','GURUBEL','MARIA DEL ROSARIO','rosario','999 361 2037','S/N','29','14','16','SAN NICOLAS','69','860','Ama de casa','68','F',' ANGRRS67061831M100','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0178','3','007','PROMOVIDOS','ANGULO','CANUL','ARON NEFTALI','aron','999 361 2037','S/N','29','14','16','SAN NICOLAS','69','860','','69','M',' ANCNAR00100531H900','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0179','3','007','PROMOVIDOS','TEC ','Y CETZ','LIDIA','doña tina','999 361 2037','96','29','20','22','GUADALUPE','45','859','Ama de casa','70','F',' TCCTLD60011731M300','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('008','2','01','ACTIVISTA','RIOS','PUCH','LUIS ADRIEL','MURO','999 552 3742','S/N','27','10','6','San Nicolas','','860','Empleado','23','M','WWWWWWWWWWWW1','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0180','3','008','PROMOVIDOS','RIOS','PUCH','NATALY XIADANY','','991 116 4106','S/N','','','','','','860','','17','M','EEEEEEEEEEEEEEEEE1','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0181','3','008','PROMOVIDOS','PUCH','PACHECO','HERMELINDA','','999 233 7767','S/N','','','','','','860','','18','M','EEEEEEEEEEEEEEEEE2','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0182','3','008','PROMOVIDOS','PUCH','TUN','CIRILO','','999 324 8358','S/N','','','','','','860','','19','M','EEEEEEEEEEEEEEEEE3','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0183','3','008','PROMOVIDOS','TORRES ','CHERRIZ','AMBAR GEOVANI','','999 540 6620','S/N','','','','','','860','','20','M','EEEEEEEEEEEEEEEEE4','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0184','3','008','PROMOVIDOS','LOPE','PUC ','PEDRO','','991 1054243','S/N','','','','','','860','','21','M','EEEEEEEEEEEEEEEEE5','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0185','3','008','PROMOVIDOS','RIOS','SAN ','JOSE LUIS','','999 433 0490','S/N','','','','','','860','','22','M','EEEEEEEEEEEEEEEEE6','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0186','3','008','PROMOVIDOS','PECH','AGUAYO','GERARDO EDUARDO','','999 173 7260','S/N','','','','','','860','','23','M','EEEEEEEEEEEEEEEEE7','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0187','3','008','PROMOVIDOS','PUC ','PALACIOS ','ROSALVA','','999 137 1413','S/N','','','','','','860','','24','F','EEEEEEEEEEEEEEEEE8','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0188','3','008','PROMOVIDOS','PUCH','PACHECO','JOSE PEDRO','','999 552 3742','S/N','','','','','','860','','25','M','EEEEEEEEEEEEEEEEE9','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0189','3','008','PROMOVIDOS','RIOS','SANSORES','BALTAZAR','','999 233 7767','S/N','','','','','','860','','26','M','EEEEEEEEEEEEEEEEE10','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0190','3','008','PROMOVIDOS','LUNA ','KU','MANUEL','','987 876 9142','S/N','','','','','','860','','27','M','EEEEEEEEEEEEEEEEE11','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0191','3','008','PROMOVIDOS','UC','CAB','PEDRO RENE','','999 186 7286','S/N','','','','','','860','','28','M','EEEEEEEEEEEEEEEEE12','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0192','3','008','PROMOVIDOS','YAH','CAMPOS','CINTHYA','','999 115 2488','S/N','','','','','','860','','29','F','EEEEEEEEEEEEEEEEE13','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0193','3','008','PROMOVIDOS','EK ','VAZQUEZ','JULIO CESAR','','999 115 2488','S/N','','','','','','860','','30','M','EEEEEEEEEEEEEEEEE14','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0194','3','008','PROMOVIDOS','EK ','VAZQUEZ','ALBERTH','','999 552 3742','S/N','','','','','','860','','31','M','EEEEEEEEEEEEEEEEE15','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0195','3','008','PROMOVIDOS','EK ','VAZQUEZ','ANA','','999 552 3742','S/N','','','','','','860','','32','F','EEEEEEEEEEEEEEEEE16','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0196','3','008','PROMOVIDOS','BAAS ','PECH','JOSE LEONARDO','','999 111 6897','S/N','','','','','','860','','33','M','EEEEEEEEEEEEEEEEE17','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0197','3','008','PROMOVIDOS','PALMA','LEON','ADRIAN','','991 110 9105','S/N','','','','','','860','','34','M','EEEEEEEEEEEEEEEEE18','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('009','2','01','ACTIVISTA','ROSADO','ROMERO','MAURICIO JAVIER','JAVI','991 106 5649','S/N','22','29','27','GUADALUPE','57','859','Empleado','45','M','WWWWWWWWWWWW2','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0198','3','009','PROMOVIDOS','ROMERO ','VARGAS','SOLEDAD DEL SOCORRO','SOL','999 260 1525','S/N','22','29','27','GUADALUPE','57','859','Ama de casa','23','F','FFFFFFFFFFFFFFFFFFFF1','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0199','3','009','PROMOVIDOS','ROSADO','POVEDANO','GUALTER','WALTER','','S/N','22','20','27','GUADALUPE','57','859','Pescador','23','M','FFFFFFFFFFFFFFFFFFFF2','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('010','2','01','ACTIVISTA','HERNANDEZ','CANCHE','PERFECTO DE JESUS','CHUY','999 498 1324','S/N','29','20','22','GUADALUPE','45','859','Profesor','32','M','HRCNPR89020431H400','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0200','3','010','PROMOVIDOS','HERNANDEZ','SALVADOR','JESUS','PASTOR','999 256 7030','S/N','29','20','22','GUADALUPE','45','859','Ministro','71','M','HRSLJS50041627H300','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0201','3','010','PROMOVIDOS','CANCHE ','KU','MARIA JUANA','MARY','999 551 4273','S/N','29','20','22','GUADALUPE','45','859','Ama de Casa','65','F',' CNKUJN56062431M600','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0202','3','010','PROMOVIDOS','CAMPOS','POOL','YUCELI NOEMI','YUCI','999 511 1717','S/N','29','22','20','GUADALUPE','45','859','Ama de Casa','34','F','CMPLYC86112231M000','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0203','3','010','PROMOVIDOS','TEP','EUAN','RITA GUADALUPE','rita','991 109 0416','S/N','29','2D','2E','GUADALUPE','107','860','Ama de casa','34','F',' TPENRT82120131M300','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0204','3','010','PROMOVIDOS','MONTALVO','TEP','YAMILI','yamili','991 959 8461','S/N','29','2D','2E','GUADALUPE','107','860','Estudiante ','21','F','SSSSSSSSSSSSSSSSS1','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0205','3','010','PROMOVIDOS','HERNANDEZ','VALENCIA','CRUZ','chuflos','991 108 6107','S/N','29','22','24','GUADALUPE','45','859','albañil','36','M',' HRVLCR70020727H600','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0206','3','010','PROMOVIDOS','HERNANDEZ','ESTRELLA','AMAIRANI','amairani','','S/N','29','22','24','GUADALUPE','45','859','Estudiante ','36','F',' HRESAM00102131M600','Telchac Pto','Telchac Pto');
insert into personaactivista(idpuesto,idrol,idjefe,puesto,apellidomaterno,apellidopaterno,nombre,alias,telefono,numero,calle,cruzamientouno,cruzamientodos,colonia,manzana,seccion,ocupacion,edad,genero,claveelector,localidad,municipio)
values('0207','3','010','PROMOVIDOS','ESTRELLA','NOH','MARIA EUGENIA','geni','991 108 6107','S/N','29','22','24','GUADALUPE','45','859','Ama de Casa','36','F',' ESNHEG76100331M700','Telchac Pto','Telchac Pto');


--Creamos usuarios con password
insert into user_access(user_name, password,  idpersonaactivista, nombre, idrol)
select idpuesto, claveelector, idpersonaactivista, nombre, idrol from personaactivista where idrol in('1','2');

--Creamos persona apoyo
insert into personaapoyo(idpersonaactivista, nombre, apellidopaterno, apellidomaterno)
select idpersonaactivista, nombre, apellidopaterno, apellidomaterno from personaactivista;


--Actualizamos password a 4 caracteres
update user_access
set password = right((idpersonaactivista::varchar), 4);


--Creamos al usuario admin
insert into user_access(user_name, password, idpersonaactivista, nombre, idrol)
values ('admin', '4570', null, 'admin', '5');


--Creamos al usuario capturista
insert into user_access(user_name, password, idpersonaactivista, nombre, idrol)
values ('capt', '7045', null, 'capt', '4');

--Creamos al usuario diag
insert into user_access(user_name, password, idpersonaactivista, nombre, idrol)
values ('diag', '7450', null, 'diag', '6');
